name: files-update
on:
  schedule:
    - cron:  '0 18 * * 1'
jobs:
  files-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Download AWS JSON
        run: |
          wget 'https://ip-ranges.amazonaws.com/ip-ranges.json' -N -O files/aws.json
      - name: Download Azure JSON
        run: |
          today='date +%u'
          if [ "$today" == "1" ]
          then
            monday=$(date -dmonday +%Y%m%d)
          else
            monday=$(date -dlast-monday +%Y%m%d)
          fi
          wget "https://download.microsoft.com/download/7/1/D/71D86715-5596-4529-9B13-DA13A5DE5B63/ServiceTags_Public_$monday.json" -N -O files/azure.json
      - name: Generate statik file
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          go get github.com/rakyll/statik
          statik -src=files -dest=pkg/ccidr -f
      - name: Generate tag name
        id: gentag
        run: |
          lastTag=$(git tag | sort -V | tail -1)
          tagName=$(echo $lastTag  | awk -F. -v OFS=. '{$NF++;print}')
          echo "::set-output name=tag_name::$tagName"
      - name: Commit new files
        uses: EndBug/add-and-commit@v4
        with:
          add: '.'
          author_name: Jean-Philippe Bond
          author_email: jeanp.bond.dev@gmail.com
          message: 'Update Public Cloud JSON files'
          tag: ${{ steps.gentag.outputs.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
